apiVersion: meridio-2.nordix.org/v1alpha1
kind: GatewayRouter
metadata:
  labels:
    app.kubernetes.io/name: meridio-2
    app.kubernetes.io/managed-by: kustomize
  name: gatewayrouter-static-sample
spec:
  gatewayRef:
    name: sllb-a
  interface: "vlan-100"
  address: "169.254.100.150"
  protocol: "Static"
  static:
    bfd:
      minTx: 300ms
      minRx: 300ms
      multiplier: 3
